<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>GetCode.Infrastructure</AssemblyName>
    <RootNamespace>GetCode.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="GetCode.ObservabilityTests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../GetCode.Application/GetCode.Application.csproj" />
    <ProjectReference Include="../GetCode.Domain/GetCode.Domain.csproj" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
