<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>GetCode.Api</AssemblyName>
    <RootNamespace>GetCode.Api</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../GetCode.Application/GetCode.Application.csproj" />
    <ProjectReference Include="../GetCode.Contracts/GetCode.Contracts.csproj" />
    <ProjectReference Include="../GetCode.Infrastructure/GetCode.Infrastructure.csproj" />
    <ProjectReference Include="../GetCode.Persistence/GetCode.Persistence.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" />
  </ItemGroup>
</Project>
