// <auto-generated />
using System;
using GetCode.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GetCode.Persistence.Migrations
{
    [DbContext(typeof(GetCodeDbContext))]
    [Migration("20260824100525_AddProviderRegistry")]
    partial class AddProviderRegistry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GetCode.Domain.Catalog.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("code")
                        .IsFixedLength();

                    b.Property<string>("DefaultDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("default_display_name");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.HasKey("Id")
                        .HasName("pk_countries");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_countries__code");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("GetCode.Domain.Catalog.ProductSku", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("country_id");

                    b.Property<bool>("IsOffered")
                        .HasColumnType("boolean")
                        .HasColumnName("is_offered");

                    b.Property<int>("ProductType")
                        .HasColumnType("integer")
                        .HasColumnName("product_type");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.HasKey("Id")
                        .HasName("pk_product_skus");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_product_skus__service_id");

                    b.HasIndex("CountryId", "ServiceId", "ProductType")
                        .IsUnique()
                        .HasDatabaseName("ix_product_skus__country_id_service_id_product_type");

                    b.ToTable("product_skus", (string)null);
                });

            modelBuilder.Entity("GetCode.Domain.Catalog.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DefaultDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("default_display_name");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_services__slug");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("GetCode.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at_utc");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_count");

                    b.Property<DateTimeOffset?>("FirstFailedLoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_failed_login_at_utc");

                    b.Property<string>("LockReason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("lock_reason");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until_utc");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<DateTimeOffset>("PasswordChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_users__normalized_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("GetCode.Domain.Providers.ProviderDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_key");

                    b.Property<bool>("SupportsActivation")
                        .HasColumnType("boolean")
                        .HasColumnName("supports_activation");

                    b.Property<bool>("SupportsRental")
                        .HasColumnType("boolean")
                        .HasColumnName("supports_rental");

                    b.HasKey("Id")
                        .HasName("pk_providers");

                    b.HasIndex("ProviderKey")
                        .IsUnique()
                        .HasDatabaseName("ix_providers__provider_key");

                    b.ToTable("providers", (string)null);
                });

            modelBuilder.Entity("GetCode.Domain.Providers.ProviderMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CanonicalId")
                        .HasColumnType("uuid")
                        .HasColumnName("canonical_id");

                    b.Property<string>("ExternalCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_code");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.HasKey("Id")
                        .HasName("pk_provider_mappings");

                    b.HasIndex("ProviderId", "Kind", "ExternalCode")
                        .IsUnique()
                        .HasDatabaseName("ix_provider_mappings__provider_id_kind_external_code");

                    b.ToTable("provider_mappings", (string)null);
                });

            modelBuilder.Entity("GetCode.Persistence.Identity.IdentityAuditEventRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("details_json");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean")
                        .HasColumnName("succeeded");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_identity_audit_events");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_identity_audit_events__event_type");

                    b.HasIndex("UserId", "OccurredAtUtc")
                        .HasDatabaseName("ix_identity_audit_events__user_id_occurred_at_utc");

                    b.ToTable("identity_audit_events", (string)null);
                });

            modelBuilder.Entity("GetCode.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_error_code");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<string>("SpanId")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("span_id");

                    b.Property<string>("TraceId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("trace_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedAtUtc", "OccurredAtUtc")
                        .HasDatabaseName("ix_outbox_messages__processed_at_utc_occurred_at_utc");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("GetCode.Domain.Catalog.Country", b =>
                {
                    b.OwnsMany("GetCode.Domain.Catalog.LocalizedCatalogName", "LocalizedNames", b1 =>
                        {
                            b1.Property<Guid>("country_id")
                                .HasColumnType("uuid")
                                .HasColumnName("country_id");

                            b1.Property<string>("CultureCode")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("culture_code");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("display_name");

                            b1.HasKey("country_id", "CultureCode")
                                .HasName("pk_country_localized_names");

                            b1.ToTable("country_localized_names", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("country_id")
                                .HasConstraintName("fk_country_localized_names_countries");
                        });

                    b.Navigation("LocalizedNames");
                });

            modelBuilder.Entity("GetCode.Domain.Catalog.ProductSku", b =>
                {
                    b.HasOne("GetCode.Domain.Catalog.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_skus_countries");

                    b.HasOne("GetCode.Domain.Catalog.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_skus_services");
                });

            modelBuilder.Entity("GetCode.Domain.Catalog.Service", b =>
                {
                    b.OwnsMany("GetCode.Domain.Catalog.LocalizedCatalogName", "LocalizedNames", b1 =>
                        {
                            b1.Property<Guid>("service_id")
                                .HasColumnType("uuid")
                                .HasColumnName("service_id");

                            b1.Property<string>("CultureCode")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("culture_code");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("display_name");

                            b1.HasKey("service_id", "CultureCode")
                                .HasName("pk_service_localized_names");

                            b1.ToTable("service_localized_names", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("service_id")
                                .HasConstraintName("fk_service_localized_names_services");
                        });

                    b.Navigation("LocalizedNames");
                });

            modelBuilder.Entity("GetCode.Domain.Providers.ProviderMapping", b =>
                {
                    b.HasOne("GetCode.Domain.Providers.ProviderDefinition", null)
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_provider_mappings_providers");
                });
#pragma warning restore 612, 618
        }
    }
}
