<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/GetCode.Application/GetCode.Application.csproj" />
    <ProjectReference Include="../../src/GetCode.Domain/GetCode.Domain.csproj" />
    <ProjectReference Include="../../src/GetCode.Infrastructure/GetCode.Infrastructure.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
</Project>
